### PR TITLE
Review 1_1 to 1_3 notebooks

### PR DESCRIPTION
**Pull request by sonjaleo**
## Description
Make changes according to Andreas notebook review

## Todos
Notable points that this PR has either accomplished or will accomplish.
Look at comments in  https://app.reviewnb.com/sonjaleo/KinFragLib/pull/2/files/#comment-diff-731717230
  - [x]  add new dataframe with fragment counts function and use it in notebooks
  - [x] add more descriptive names for dataframes than d in 1_1, 1_2 and 1_3
  - [x] add other input parameters
  - [x] add description above counting accepted and rejected cells
  - [x] check code and documentation
  - [x] create RADME.md for custom_kinfraglib
  - [x] add " Analyse accepted/rejected fragments" bullet points whats done
 
notebook 1_3
- [x] name linking more explicit : (SYBA github repo)[https://github.com/lich-uct/syba]
- [x] correct last sentence SYBA
- [x] show docstring of calc_syba
- [x]  add description to histograms
- [x] change bb comparison to only comparing molecules
- [x] change syba function using molecules (SMILES optional)

## Status
- [x] Ready to go

### CODE REVIEW

**Review by AndreaVolkamer — COMMENTED** [review]
Started the review.

Updates on 1_1
*  small textual adaptions included (please check)
* merged pains.py content to unwanted_substructures.py

Question:
* I get a warning when importing the libraries, please check: 

`<frozen importlib._bootstrap>:219: RuntimeWarning: to-Python converter for boost::shared_ptr<RDKit::FilterCatalogEntry const> already registered; second conversion method ignored.`

**Comment by AndreaVolkamer** [comment]
Updates on 1_2
* small textual adaptions included (please check)
* merged qed.py and ro3.py content in drug_likeness.py

Todos:
* Please explain individual steps in helper functions (.py) a bit more (add inline comments)
* Adapt QED description wording in nb

**Comment by AndreaVolkamer** [comment]
Updates 1_3
* small textual adaptions included (please check)

Todos:
* check description in `check_building_blocks`doc string
* in `calc_syba` parameter for new column_name given, not available for all previous functions, make consistent (easiest: delete it here) 
* [tbd] one could merge syba.py and building_blocks.py content in synthesizability.py

**Comment by AndreaVolkamer** [comment]
@sonjaleo the notebooks look/read nice and run without problems

* See my comments to the individual three parts above
* Please use a spellchecker to go through all 3 notebooks and especially also the xxx.py files
* In most functions, in the filter xxx.py files a bit of guidance what the code does (inline comments) would be helpful

TODO (to be tackled in a new PR)
* Add or update READMEs on the diverse levels to include the new custom-KinFragLib information/data

**Comment by sonjaleo** [comment]
> Started the review.
> 
> Updates on 1_1
> 
> * small textual adaptions included (please check)
> * merged pains.py content to unwanted_substructures.py
> 
> Question:
> 
> * I get a warning when importing the libraries, please check:
> 
> `<frozen importlib._bootstrap>:219: RuntimeWarning: to-Python converter for boost::shared_ptr<RDKit::FilterCatalogEntry const> already registered; second conversion method ignored.`

This warning is also shown in https://projects.volkamerlab.org/teachopencadd/talktorials/T003_compound_unwanted_substructures.html
so it doesn't seem to be a problem with my code.

**Comment by sonjaleo** [comment]
@AndreaVolkamer  I think I did everything you mentioned. Do you want to have a final check or should I just merge it into custom-base?

**Comment by AndreaVolkamer** [comment]
@sonjaleo thanks! ready to be merged!

**Pull request merged**
