### PR TITLE
PR for analysis

### PR DESCRIPTION
**Pull request by sonjaleo**
## Description
Analyse filtering steps and filtered fragment library.
To keep comparable do analysis like in 
https://github.com/volkamerlab/KinFragLib/blob/master/notebooks/2_2_fragment_analysis_statistics.ipynb
https://github.com/volkamerlab/KinFragLib/blob/master/notebooks/2_3_fragment_analysis_most_common_fragments.ipynb

## Todos
2_2_custom_filters_analysis
  - [x] read in fragment_library, fragment_library_reduced [and fragment_library_custom]
  - [x] write function comparing which fragments are in which subset
  - [x] t-sne plots
  - [x] fragment similarity between and across kinase groups
  - [x] fragment similarity per subpocket
  - [x] fragment properties
  - [x] conncetion frequency
  - [ ] most common and most specific fragments per subpocket

notebook 1_1_unwanted substructures
  - [x] highlight unwanted substructures in fragments

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by AndreaVolkamer** [comment]
@sonjaleo well done. Nice analysis notebook.

Note I did not run it, just checked it on review nb.
I still want to look at the cluster results when playing with the subpocket nr ... but you can go ahead with implementing the review comments in the meantime.

**Comment by sonjaleo** [comment]
<blockquote>-&gt; something missing here:</blockquote><p>Not sure what you mean?</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sonjaleo** [comment]
<p>I am checking with the pre-filtered fragment library which fragments from this pre-filtered fragment library are also in the reduced and in the custom subset. We need this information for the t-sne plots</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sonjaleo** [comment]
<p>e.g. something like "Comparing chemical space spanned by the libraries"?</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sonjaleo** [comment]
<p>When you run it locally, you should see it. Seems to be too large to be displayed on GitHub.</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sonjaleo** [comment]
<p>It's called fragment_count because I use the function from Paula, but I can change it after calling Paula's function. I think this would really make more sense!</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sonjaleo** [comment]
<p>I changed the names to 'syba filtered', 'pains filtered' and so on</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sonjaleo** [comment]
<p>Any ideas for the function name? specificity_of_most_common or something like this?</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AndreaVolkamer** [comment]
<p>This sentence does not make sense to me: 'Check which fragments from are contained in the subsets'</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AndreaVolkamer** [comment]
<p>Same comment as before, the sentence seems to be wrong 'Check which fragments from are contained in the subsets'</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AndreaVolkamer** [comment]
<p>'... which fragments from' what? E.g. '... which fragments from the original library'? </p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AndreaVolkamer** [comment]
<p>yes</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AndreaVolkamer** [comment]
<p>ok</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AndreaVolkamer** [comment]
<p>maybe include the docstring first, what is exactly calculated that should help to come up with a good name</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AndreaVolkamer** [comment]
<p>great!</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sonjaleo** [comment]
<p>I included your comments.</p><p>Could you please have another look?</p><p>Especially, it would be nice if you could comment on </p><p>1) 3.3. Where I added a feature that not only the subpocket count but also the subpockets can be displayed under the fragments. If you think we don't need this, it's fine, I can just remove it. If we want to keep it, we can either leave it as it is (should it be shown for the others as well?) or we could remove the number of subpockets when showing the subpockets because it is a bit repetitive.</p><p>I also added a line</p><p>2) 3.5. I left the function there for you to look at it. I set num_subpockets to 6 because now that we show the number of subpockets occupied by each fragment one can see which of them are more specific or less. Furthermore, I also changed the function name to most_common_in_subset because as you say it could be the most specific or least specific fragments of the subsets</p><p>3) should I do the analysis in 3.5. also for the reduced and the pre-filtered subsets??</p>

**Comment by AndreaVolkamer** [comment]
@sonjaleo thanks looks great!

1. to 3.3: I like the new outputs, I would also keep them both, but suggest to
   - change the order of the two: go from more general (all subpockets) to specific (only one subpocket, here AP) analysis
   - and extend the textual description a bit, what is calculated/shown there, point explicitly to the fact that once it's done for all subpockets, and then only the results per subpockets are shown
2. to 3.5. looks great to me!
3. The analysis is enough for your custom library.

**Pull request merged**
