### PR TITLE
Find matching fragment pairs

### PR DESCRIPTION
**Pull request by sonjaleo**
## Description
Find matching fragment pairs

## Todos
Conditions need to be checked
  - [x] dummy atoms have complementary subpockets
  - [x] dummy atoms have identical BRICS environment
  - [x] dummy atoms have same bond type
  - [x] write function to get valid fragment pairs (with above conditions)
  - [x] write function to get askcos results 
  - [x] 2 pairs are missing because they are substrings of other pairs SMILES -> fix this
  - [x] write function to compare results children with fragments
  - [x] write documentation for functions
  - [x] clean up code
  - [x] Add texts to notebook

## Questions
- [ ] Question1

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by dominiquesydow** [comment]
Hi @sonjaleo, I think you need my review later, right? Please ping me again when I shall take a look :)

**Comment by sonjaleo** [comment]
> Hi @sonjaleo, I think you need my review later, right? Please ping me again when I shall take a look :)

Yes, only added you that you can have a look in between when you are curious :) I'll ping you when I need you

**Review by AndreaVolkamer — APPROVED** [review]
@sonjaleo Looks good, feedback on 
* mainly adding a bit more textual info via NB review, 
* and one function for the analysis part, see comments above.
Afterwards ready to be merged!

**Comment by sonjaleo** [comment]
<p>No, I did the ASKCOS query already for 46512 pairs which are stored in /data/filters/retrosynthesizability/retro.txt.</p><p>I added the link to the file</p>

---

 <a href='https://app.reviewnb.com/sonjaleo/KinFragLib/pull/9/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
