### PR TITLE
nb 1_1 style corrected

### PR DESCRIPTION
**Pull request by sonjaleo**
## Description
correct code style of existing notebooks
## Todos
  - [x] correct 1_1_custom_filters_unwanted_substructures.ipynb
  - [x] correct 1_2_custom_filters_drug_likeness.ipynb
  - [x] correct 1_3_custom_filters_synthesizability.ipynb

## Questions
- [x] @dominiquesydow maybe I need help with merging because in nb 1_3 there are also changes in the readme-DataWarrior branch

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by dominiquesydow** [comment]
Hi @sonjaleo,

> @dominiquesydow maybe I need help with merging because in nb 1_3 there are also changes in the readme-DataWarrior branch

Right now there are no conflicts but you mean this branch may be in conflict with another branch branched off `custom-base`?

**Comment by dominiquesydow** [comment]
I see you mean the conflict with #7. 
I would touch notebook 1_3 only in one of these PRs (#7 and #8) because conflicts in Jupyter notebooks are a bit painful.

Since this PR here is only about style, I might reset 1_3 in this PR to it's `custom-base` version - and reapply the style in #7 (and add a comment about his in this PR's description).

**Comment by dominiquesydow** [comment]
Also, to make notebook reviews easier: could you check if you have ReviewNB installed for your repo?

image

**Comment by sonjaleo** [comment]
> I see you mean the conflict with #7.
> I would touch notebook 1_3 only in one of these PRs (#7 and #8) because conflicts in Jupyter notebooks are a bit painful.
> 
> Since this PR here is only about style, I might reset 1_3 in this PR to it's `custom-base` version - and reapply the style in #7 (and add a comment about his in this PR's description).

yes that was the conflict I mean.
Could we maybe do this together on wednesday or thursday, if you have time? @dominiquesydow

**Comment by sonjaleo** [comment]
> Also, to make notebook reviews easier: could you check if you have ReviewNB installed for your repo?
> 
> image

just installed it :)

**Pull request merged**
